from typing import Annotated, TypedDict, List, Dict, Any
from langgraph.graph.message import add_messages
from typing import Annotated
from langgraph.graph import StateGraph 

# state definition for the graph
class state(TypedDict, total=False):
    input: str                                          # user input query
    user_id: str                                        # unique identifier for the user
    memories_to_write: List[Dict[str, Any]]             # memories to be written
    questions: List[Dict[str, Any]]                     # questions to be asked
    ignore: List[Dict[str, Any]]                        # text to ignore
    retrieved_memories: List[Dict[str, Any]]            # memories retrieved from the memory store
    final_answer: str | None                            # final answer generated by the LLM